version: '3.7'

services:
  postgres:
    image: postgres:10.7-alpine
    ports: 
    - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_DB=acnh
      - POSTGRES_PASSWORD=admin
  pgadmin:
    image: dpage/pgadmin4:4.8
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 3004:80
    depends_on:
      - postgres
    logging:
      driver: none